FROM maven:3.9.3-eclipse-temurin-17-alpine

RUN apk update && apk upgrade

RUN apk add chromium
RUN apk add chromium-chromedriver

ARG CHROMDRIVER_VERSION=114.0.5735.90

RUN apk add bash

RUN wget -O /usr/bin/chromedriver https://chromedriver.storage.googleapis.com/$CHROMDRIVER_VERSION/chromedriver_linux64.zip
RUN unzip /usr/bin/chromedriver -d /usr/local/bin
RUN chmod +x /usr/local/bin


COPY . /usr/src/mymaven
WORKDIR /usr/src/mymaven

RUN mvn dependency:resolve
CMD ["mvn", "test"]

# CMD ["chromium", "--version"]